//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XHexEditor.Wpf.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XHexEditor.Wpf.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight.
        /// </summary>
        public static string MenuItem_Highlight {
            get {
                return ResourceManager.GetString("MenuItem_Highlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Highlight Selection.
        /// </summary>
        public static string MenuItem_HighlightSelection {
            get {
                return ResourceManager.GetString("MenuItem_HighlightSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Next Bookmark.
        /// </summary>
        public static string MenuItem_NextBookmark {
            get {
                return ResourceManager.GetString("MenuItem_NextBookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Previous Bookmark.
        /// </summary>
        public static string MenuItem_PrevBookmark {
            get {
                return ResourceManager.GetString("MenuItem_PrevBookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Remove All Highlights.
        /// </summary>
        public static string MenuItem_RemoveAllHighlights {
            get {
                return ResourceManager.GetString("MenuItem_RemoveAllHighlights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Remove Highlight.
        /// </summary>
        public static string MenuItem_RemoveHighlight {
            get {
                return ResourceManager.GetString("MenuItem_RemoveHighlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Toggle Bookmark.
        /// </summary>
        public static string MenuItem_ToggleBookmark {
            get {
                return ResourceManager.GetString("MenuItem_ToggleBookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        public static string MenuItem_Zoom {
            get {
                return ResourceManager.GetString("MenuItem_Zoom", resourceCulture);
            }
        }
    }
}
